# type: ignore
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import eraftpb_pb2 as eraftpb__pb2
from . import raft_service_pb2 as raft__service__pb2


class RaftServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MemberBootstrapReady = channel.unary_unary(
            "/raftservice.RaftService/MemberBootstrapReady",
            request_serializer=raft__service__pb2.MemberBootstrapReadyArgs.SerializeToString,
            response_deserializer=raft__service__pb2.MemberBootstrapReadyResponse.FromString,
        )
        self.ClusterBootstrapReady = channel.unary_unary(
            "/raftservice.RaftService/ClusterBootstrapReady",
            request_serializer=raft__service__pb2.ClusterBootstrapReadyArgs.SerializeToString,
            response_deserializer=raft__service__pb2.ClusterBootstrapReadyResponse.FromString,
        )
        self.RequestId = channel.unary_unary(
            "/raftservice.RaftService/RequestId",
            request_serializer=raft__service__pb2.IdRequestArgs.SerializeToString,
            response_deserializer=raft__service__pb2.IdRequestResponse.FromString,
        )
        self.ChangeConfig = channel.unary_unary(
            "/raftservice.RaftService/ChangeConfig",
            request_serializer=eraftpb__pb2.ConfChangeV2.SerializeToString,
            response_deserializer=raft__service__pb2.ChangeConfigResponse.FromString,
        )
        self.ApplyConfigChangeForcely = channel.unary_unary(
            "/raftservice.RaftService/ApplyConfigChangeForcely",
            request_serializer=eraftpb__pb2.ConfChangeV2.SerializeToString,
            response_deserializer=raft__service__pb2.ChangeConfigResponse.FromString,
        )
        self.SendMessage = channel.unary_unary(
            "/raftservice.RaftService/SendMessage",
            request_serializer=eraftpb__pb2.Message.SerializeToString,
            response_deserializer=raft__service__pb2.Empty.FromString,
        )
        self.Propose = channel.unary_unary(
            "/raftservice.RaftService/Propose",
            request_serializer=raft__service__pb2.ProposeArgs.SerializeToString,
            response_deserializer=raft__service__pb2.ProposeResponse.FromString,
        )
        self.RerouteMessage = channel.unary_unary(
            "/raftservice.RaftService/RerouteMessage",
            request_serializer=raft__service__pb2.RerouteMessageArgs.SerializeToString,
            response_deserializer=raft__service__pb2.ProposeResponse.FromString,
        )
        self.GetPeers = channel.unary_unary(
            "/raftservice.RaftService/GetPeers",
            request_serializer=raft__service__pb2.Empty.SerializeToString,
            response_deserializer=raft__service__pb2.GetPeersResponse.FromString,
        )
        self.DebugNode = channel.unary_unary(
            "/raftservice.RaftService/DebugNode",
            request_serializer=raft__service__pb2.Empty.SerializeToString,
            response_deserializer=raft__service__pb2.DebugNodeResponse.FromString,
        )
        self.DebugEntries = channel.unary_unary(
            "/raftservice.RaftService/DebugEntries",
            request_serializer=raft__service__pb2.Empty.SerializeToString,
            response_deserializer=raft__service__pb2.DebugEntriesResponse.FromString,
        )
        self.Version = channel.unary_unary(
            "/raftservice.RaftService/Version",
            request_serializer=raft__service__pb2.Empty.SerializeToString,
            response_deserializer=raft__service__pb2.VersionResponse.FromString,
        )


class RaftServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MemberBootstrapReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClusterBootstrapReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequestId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChangeConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ApplyConfigChangeForcely(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RerouteMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DebugNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DebugEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "MemberBootstrapReady": grpc.unary_unary_rpc_method_handler(
            servicer.MemberBootstrapReady,
            request_deserializer=raft__service__pb2.MemberBootstrapReadyArgs.FromString,
            response_serializer=raft__service__pb2.MemberBootstrapReadyResponse.SerializeToString,
        ),
        "ClusterBootstrapReady": grpc.unary_unary_rpc_method_handler(
            servicer.ClusterBootstrapReady,
            request_deserializer=raft__service__pb2.ClusterBootstrapReadyArgs.FromString,
            response_serializer=raft__service__pb2.ClusterBootstrapReadyResponse.SerializeToString,
        ),
        "RequestId": grpc.unary_unary_rpc_method_handler(
            servicer.RequestId,
            request_deserializer=raft__service__pb2.IdRequestArgs.FromString,
            response_serializer=raft__service__pb2.IdRequestResponse.SerializeToString,
        ),
        "ChangeConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ChangeConfig,
            request_deserializer=eraftpb__pb2.ConfChangeV2.FromString,
            response_serializer=raft__service__pb2.ChangeConfigResponse.SerializeToString,
        ),
        "ApplyConfigChangeForcely": grpc.unary_unary_rpc_method_handler(
            servicer.ApplyConfigChangeForcely,
            request_deserializer=eraftpb__pb2.ConfChangeV2.FromString,
            response_serializer=raft__service__pb2.ChangeConfigResponse.SerializeToString,
        ),
        "SendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=eraftpb__pb2.Message.FromString,
            response_serializer=raft__service__pb2.Empty.SerializeToString,
        ),
        "Propose": grpc.unary_unary_rpc_method_handler(
            servicer.Propose,
            request_deserializer=raft__service__pb2.ProposeArgs.FromString,
            response_serializer=raft__service__pb2.ProposeResponse.SerializeToString,
        ),
        "RerouteMessage": grpc.unary_unary_rpc_method_handler(
            servicer.RerouteMessage,
            request_deserializer=raft__service__pb2.RerouteMessageArgs.FromString,
            response_serializer=raft__service__pb2.ProposeResponse.SerializeToString,
        ),
        "GetPeers": grpc.unary_unary_rpc_method_handler(
            servicer.GetPeers,
            request_deserializer=raft__service__pb2.Empty.FromString,
            response_serializer=raft__service__pb2.GetPeersResponse.SerializeToString,
        ),
        "DebugNode": grpc.unary_unary_rpc_method_handler(
            servicer.DebugNode,
            request_deserializer=raft__service__pb2.Empty.FromString,
            response_serializer=raft__service__pb2.DebugNodeResponse.SerializeToString,
        ),
        "DebugEntries": grpc.unary_unary_rpc_method_handler(
            servicer.DebugEntries,
            request_deserializer=raft__service__pb2.Empty.FromString,
            response_serializer=raft__service__pb2.DebugEntriesResponse.SerializeToString,
        ),
        "Version": grpc.unary_unary_rpc_method_handler(
            servicer.Version,
            request_deserializer=raft__service__pb2.Empty.FromString,
            response_serializer=raft__service__pb2.VersionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "raftservice.RaftService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MemberBootstrapReady(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/MemberBootstrapReady",
            raft__service__pb2.MemberBootstrapReadyArgs.SerializeToString,
            raft__service__pb2.MemberBootstrapReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ClusterBootstrapReady(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/ClusterBootstrapReady",
            raft__service__pb2.ClusterBootstrapReadyArgs.SerializeToString,
            raft__service__pb2.ClusterBootstrapReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RequestId(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/RequestId",
            raft__service__pb2.IdRequestArgs.SerializeToString,
            raft__service__pb2.IdRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ChangeConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/ChangeConfig",
            eraftpb__pb2.ConfChangeV2.SerializeToString,
            raft__service__pb2.ChangeConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ApplyConfigChangeForcely(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/ApplyConfigChangeForcely",
            eraftpb__pb2.ConfChangeV2.SerializeToString,
            raft__service__pb2.ChangeConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/SendMessage",
            eraftpb__pb2.Message.SerializeToString,
            raft__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Propose(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/Propose",
            raft__service__pb2.ProposeArgs.SerializeToString,
            raft__service__pb2.ProposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RerouteMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/RerouteMessage",
            raft__service__pb2.RerouteMessageArgs.SerializeToString,
            raft__service__pb2.ProposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetPeers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/GetPeers",
            raft__service__pb2.Empty.SerializeToString,
            raft__service__pb2.GetPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DebugNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/DebugNode",
            raft__service__pb2.Empty.SerializeToString,
            raft__service__pb2.DebugNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DebugEntries(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/DebugEntries",
            raft__service__pb2.Empty.SerializeToString,
            raft__service__pb2.DebugEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Version(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/raftservice.RaftService/Version",
            raft__service__pb2.Empty.SerializeToString,
            raft__service__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
