# type: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import eraftpb_pb2 as eraftpb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12raft_service.proto\x12\x0braftservice\x1a\reraftpb.proto"\x19\n\x08Proposal\x12\r\n\x05inner\x18\x01 \x01(\x0c"H\n\x11IdRequestResponse\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x17.raftservice.ResultCode\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c"\x07\n\x05\x45mpty"#\n\x05\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\t"\x1d\n\x0cRaftResponse\x12\r\n\x05inner\x18\x02 \x01(\x0c*0\n\nResultCode\x12\x06\n\x02Ok\x10\x00\x12\t\n\x05\x45rror\x10\x01\x12\x0f\n\x0bWrongLeader\x10\x02\x32\xd0\x01\n\x0bRaftService\x12\x41\n\tRequestId\x12\x12.raftservice.Empty\x1a\x1e.raftservice.IdRequestResponse"\x00\x12@\n\x0c\x43hangeConfig\x12\x13.eraftpb.ConfChange\x1a\x19.raftservice.RaftResponse"\x00\x12<\n\x0bSendMessage\x12\x10.eraftpb.Message\x1a\x19.raftservice.RaftResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "raft_service_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _RESULTCODE._serialized_start = 228
    _RESULTCODE._serialized_end = 276
    _PROPOSAL._serialized_start = 50
    _PROPOSAL._serialized_end = 75
    _IDREQUESTRESPONSE._serialized_start = 77
    _IDREQUESTRESPONSE._serialized_end = 149
    _EMPTY._serialized_start = 151
    _EMPTY._serialized_end = 158
    _ENTRY._serialized_start = 160
    _ENTRY._serialized_end = 195
    _RAFTRESPONSE._serialized_start = 197
    _RAFTRESPONSE._serialized_end = 226
    _RAFTSERVICE._serialized_start = 279
    _RAFTSERVICE._serialized_end = 487
# @@protoc_insertion_point(module_scope)
